export default {
  "app": {
    "title": "",
    "subtitle": "",
    "noResults": ""
  },
  "introPage": {
    "section1Title": "",
    "p0": "",
    "p05": "",
    "p1": "",
    "ol1": {
      "li1": "",
      "li2": "",
      "li3": ""
    },
    "section2Title": "",
    "p2": "",
    "section25Title": "",
    "p25": "",
    "section3Title": "",
    "p3": "",
    "section4Title": "",
    "p4": "",
    "section5Title": "",
    "p5": "",
    "feedbackForm": ""
  },
  "cards": {
    "table1Intro": "",
    "table2Intro": ""
  },
  "service": "",
  "slidingScale": "",
  "slidingScaleNull": "",
  "ageSpecificServices": "",
  "otherServices": "",
  "ageSpecificServicesEmpty": "",
  "otherServicesEmpty": "",
  "ageRange": {
    "category": "",
    "adult": "",
    "child": "",
    "adults": "",
    "children": ""
  },
  "patientType": {
    "category": "",
    "patient_type_new": "",
    "patient_type_existing": "",
    "patient_type_existing_only": ""
  },
  "visitType": {
    "category": "",
    "well": "",
    "sick": "",
    "sports": "",
    "prenatal": "",
    "women": "",
    "telehealth": "",
    "vaccine": ""
  },
  "tests": {
    "category": "",
    "noTests": "",
    "blood": "",
    "sti": "",
    "covid": "",
    "mammo": "",
    "xray": ""
  },
  "specialty": {
    "category": "",
    "mental": "",
    "dental": "",
    "eye": "",
    "podiatry": "",
    "mat": "",
    "nutrition": "",
    "tobacco": "",
    "pharmacy": ""
  },
  "waitTime": {
    "category": "",
    "walkIn": "",
    "oneWeekWell": "",
    "oneWeekSick": "",
    "twoMonths": ""
  },
  "transit": {
    "bus": "",
    "subway": {
      "label": "",
      "BSL": "",
      "MLF": ""
    },
    "regRail": {
      "label": "",
      "AL": "",
      "CHE": "",
      "CHW": "",
      "CL": "",
      "FC": "",
      "GC": "",
      "LD": "",
      "PM": "",
      "MN": "",
      "ME": "",
      "PT": "",
      "TL": "",
      "WL": "",
      "WTL": "",
      "WN": "",
      "FR": ""
    },
    "trolley": "",
    "car": {
      "label": "",
      "OST": "",
      "MOST": "",
      "GP": "",
      "FG": "",
      "OS": "",
      "FOS": "",
      "RV": "",
      "PL": ""
    }
  },
  "tooltips": {
    "well": "",
    "mat": "",
    "women": ""
  },
  "warnings": {
    "This health center only offers HIV and STD/STI testing and treatment; walk-ins only ": "",
    "No in-person visits available.": "",
    "This health center only sees people who are living with HIV.": "",
    "COVID-19 vaccines and testing are available to everyone. For all other services, this health center only sees people who are immigrants, undocumented, or who speak Spanish.": "",
    "Telehealth appointments for established patients only. New patient telehealth appointments available only for patients starting Hep C treatment.": "",
    "New patients should call on the first Wednesday of the month to make an appointment.": "",
    "The pharmacy is currently closed for construction": ""
  },
  "exceptions": {
    "Open first and third Saturday of each month": "",
    "Patients seen by appointment only from 4:30 p.m. - 8 p.m.": "",
    "Telehealth visits only": "",
    "On first Wednesday of the month, clinic opens at 1 p.m.": "",
    "Open until 8 p.m. by appointment only ": "",
    "Closed noon - 1 p.m.": "",
    "Closed at noon for lunch": "",
    "Urgent care available from 10:30 a.m. - 2 p.m.": "",
    "On second Friday of the month, clinic closes at 1 p.m.": "",
    "On second Saturday of the month, clinic is open from 10 a.m. to 2 p.m. ": "",
    "Patients seen by appointment only until 7:30 p.m. on the first and third Thursdays of the month": "",
    "Open first and third Thursday of each month from 5 p.m. - 7:30 p.m. (appointment only)": "",
    "Open on second Saturday of the month": "",
    "Telehealth available 5 p.m. - 7 p.m.": "",
    "Closes at noon on the third Thursday of every month, Telehealth available 5 p.m. - 7 p.m.": "",
    "Dental available 8:30 a.m. - 1 p.m. every third Saturday": "",
    "Open every fourth Saturday of the month for primary care and podiatry": "",
    "Open 8:30 a.m. - 1 p.m. every second and fourth Saturday of the month": "",
    "Dental and pediatric services available 8:30 a.m. - 1 p.m. every second and fourth Saturday of the month": "",
    "Open 8:30 a.m. - 12 p.m. every third Friday of the month": "",
    "Open 8:30 a.m. - 12 p.m. every third Saturday of the month": "",
    "On fourth Friday of the month, clinic opens from 10 a.m. - 5 p.m.": "",
    "On fourth Friday of the month, clinic opens 10 a.m. - 5 p.m.": "",
    "Closed 4 p.m. - 5 p.m.": "",
    "Closes at 1 p.m. every second Friday of the month": "",
    "Closes at noon on the third Thursday of every month": "",
    "On 2nd and 4th Tuesday of the month, clinic is open from 7:30 a.m. - 8:00 p.m. ": "",
    "On 2nd Thursday of the month, clinic is open from 9:00 a.m. - 5:00 p.m.": "",
    "On 2nd Friday of the month, clinic is open from 1:30 p.m. - 5:00 p.m.": "",
    "On second and fourth Saturday of the month, clinic is open from 8:30 a.m. - 1 p.m. for dental services": "",
    "Evening telehealth services 5 p.m. - 8 p.m.": "",
    "Evening Telehealth service 5 p.m. to 7 p.m.": "",
    "Evening telehealth services 5 p.m. - 8 p.m. Open every fourth Saturday of the month for primary care and podiatry": "",
    "On third Thursday of the month, clinic is closed": "",
    "Closed noon - 1 p.m.  On second Friday of the month, clinic closes at noon." : "",
    "On second Friday of the month, clinic closes at noon": "",
    "Open 5 p.m. to 8 p.m. by appointment only": "",
    "Select Saturdays by appointment only": "",
    "Open until 7 p.m. by appointment only": "",
    "On first and third Thursday of the month, clinic is open until 7:30 p.m.": "",
    "Evening telehealth services available 5 p.m. - 6 p.m.": "",
    "Dental services available 8:30 a.m. - 1 p.m.": "",
    "Evening telehealth services available 5 p.m. - 7 p.m.": "",
    "Open every first and third Saturday of the month": "",
    "Medical services are provided Thursday evenings only": ""
  },
  "closed": "",
  "closed*": "",
  "slidingScaleExplanation": "",
  "share": "",
  "results": "",
  "outOf": "",
  "backToHome": "",
  "back": "",
  "currentLocation": "",
  "useCurrentLocation": "",
  "searchBar": "",
  "searchButton": "",
  "otherLanguages": "",
  "tableNoData": {
    "noSpecializedServices": "",
    "noOtherServices": "",
    "noHours": ""
  }
}